FROM nginx:alpine

COPY ["fichier configuration/nginx.conf", "/etc/nginx/nginx.conf"]
COPY ["site html/", "/usr/share/nginx/html/"]

RUN chmod 644 /etc/nginx/nginx.conf \
	&& find /usr/share/nginx/html -type d -exec chmod 755 {} \; \
	&& find /usr/share/nginx/html -type f -exec chmod 644 {} \;
