apiVersion: 1

datasources:
  - name: InfluxDB-Kelonia
    uid: influxdb-kelonia
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: true
    jsonData:
      version: Flux
      organization: kelonia
      defaultBucket: kelonia
      tlsSkipVerify: true
    secureJsonData:
      token: kelonia-super-token
