[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = true

[[inputs.mqtt_consumer]]
  servers = ["tcp://${MQTT_BROKER}:${MQTT_PORT}"]
  topics = ["${MQTT_TOPIC}"]
  qos = 0
  data_format = "json"
  name_override = "telemetry"
  tag_keys = ["nid"]

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUXDB_TOKEN}"
  organization = "${INFLUXDB_ORG}"
  bucket = "${INFLUXDB_BUCKET}"
