[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = true

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["kelo/nid/+/telemetry"]
  qos = 0
  connection_timeout = "30s"
  data_format = "json"
  name_override = "telemetry"
  tag_keys = ["nid"]
  json_time_key = "horodatage"
  json_time_format = "2006-01-02T15:04:05Z07:00"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "$INFLUXDB_TOKEN"
  organization = "$INFLUXDB_ORG"
  bucket = "$INFLUXDB_BUCKET"
